# 6CS012 - Worksheet 0
## A Tutorial and Assessment on Python and NumPy for Deep Learning
**Prepared by:** Siman Giri | **Module:** 6CS012 - Artificial Intelligence and Machine Learning

---

# Section 4: TO-DO Tasks
## 4.1 Exercise on Functions

### Task 1 — Unit Converter

In [1]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'mtf' for meters to feet, 'ftm' for feet to meters.
    Returns:
        float: The converted value.
    """
    if direction == 'mtf':
        return value * 3.28084
    elif direction == 'ftm':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'mtf' or 'ftm'.")


def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'ktl' for kg to lbs, 'ltk' for lbs to kg.
    Returns:
        float: The converted value.
    """
    if direction == 'ktl':
        return value * 2.20462
    elif direction == 'ltk':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'ktl' or 'ltk'.")


def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'ltg' for liters to gallons, 'gtl' for gallons to liters.
    Returns:
        float: The converted value.
    """
    if direction == 'ltg':
        return value * 0.264172
    elif direction == 'gtl':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'ltg' or 'gtl'.")


def unit_converter():
    """
    Prompts the user to select a conversion type, enter a value,
    and displays the converted result. Handles invalid input using try-except.
    """
    print("=" * 40)
    print("       UNIT CONVERTER")
    print("=" * 40)
    print("Choose conversion type:")
    print("1. Length  (meters <-> feet)")
    print("2. Weight  (kg <-> lbs)")
    print("3. Volume  (liters <-> gallons)")

    try:
        choice = input("Enter 1, 2, or 3: ").strip()

        if choice == '1':
            print("a. Meters to Feet\nb. Feet to Meters")
            sub = input("Enter a or b: ").strip().lower()
            value = float(input("Enter value: "))
            if sub == 'a':
                result = convert_length(value, 'mtf')
                print(f"\n{value} meters = {result:.4f} feet")
            elif sub == 'b':
                result = convert_length(value, 'ftm')
                print(f"\n{value} feet = {result:.4f} meters")
            else:
                print("Invalid sub-choice.")

        elif choice == '2':
            print("a. Kilograms to Pounds\nb. Pounds to Kilograms")
            sub = input("Enter a or b: ").strip().lower()
            value = float(input("Enter value: "))
            if sub == 'a':
                result = convert_weight(value, 'ktl')
                print(f"\n{value} kg = {result:.4f} lbs")
            elif sub == 'b':
                result = convert_weight(value, 'ltk')
                print(f"\n{value} lbs = {result:.4f} kg")
            else:
                print("Invalid sub-choice.")

        elif choice == '3':
            print("a. Liters to Gallons\nb. Gallons to Liters")
            sub = input("Enter a or b: ").strip().lower()
            value = float(input("Enter value: "))
            if sub == 'a':
                result = convert_volume(value, 'ltg')
                print(f"\n{value} liters = {result:.4f} gallons")
            elif sub == 'b':
                result = convert_volume(value, 'gtl')
                print(f"\n{value} gallons = {result:.4f} liters")
            else:
                print("Invalid sub-choice.")
        else:
            print("Unsupported conversion type. Please enter 1, 2, or 3.")

    except ValueError as e:
        print(f"Invalid input: {e}")


unit_converter()

       UNIT CONVERTER
Choose conversion type:
1. Length  (meters <-> feet)
2. Weight  (kg <-> lbs)
3. Volume  (liters <-> gallons)
Enter 1, 2, or 3: 1
a. Meters to Feet
b. Feet to Meters
Enter a or b: a
Enter value: 34

34.0 meters = 111.5486 feet


### Task 2 — Mathematical Operations on a List

In [2]:
def compute_sum(numbers):
    """
    Computes the sum of a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The sum of all elements.
    """
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Computes the average of a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The average (mean) of all elements.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot compute average of an empty list.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The maximum value.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find max of an empty list.")
    max_val = numbers[0]
    for n in numbers:
        if n > max_val:
            max_val = n
    return max_val


def compute_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The minimum value.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find min of an empty list.")
    min_val = numbers[0]
    for n in numbers:
        if n < min_val:
            min_val = n
    return min_val


def math_operations():
    """
    Prompts user to choose a math operation and input a list of numbers.
    Performs the selected operation and displays the result.
    Handles errors using try-except.
    """
    print("=" * 40)
    print("   MATHEMATICAL LIST OPERATIONS")
    print("=" * 40)
    print("Choose an operation:")
    print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

    try:
        choice = input("Enter 1, 2, 3, or 4: ").strip()
        raw = input("Enter numbers separated by spaces: ").strip()

        if not raw:
            raise ValueError("Empty input. Please enter at least one number.")

        numbers = [float(x) for x in raw.split()]

        if choice == '1':
            print(f"\nSum = {compute_sum(numbers)}")
        elif choice == '2':
            print(f"\nAverage = {compute_average(numbers):.4f}")
        elif choice == '3':
            print(f"\nMaximum = {compute_maximum(numbers)}")
        elif choice == '4':
            print(f"\nMinimum = {compute_minimum(numbers)}")
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")

    except ValueError as e:
        print(f"Error: {e}")


math_operations()

   MATHEMATICAL LIST OPERATIONS
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 1
Enter numbers separated by spaces: 2 2 4 6 7

Sum = 21.0


---
## 4.2 Exercise on List Manipulation

In [3]:
def extract_every_other(lst):
    """
    Returns every other element from lst starting from index 0.
    Parameters:
        lst (list): Input list.
    Returns:
        list: Every other element.
    """
    return lst[::2]

print("1. Extract Every Other Element:")
print(extract_every_other([1, 2, 3, 4, 5, 6]))

1. Extract Every Other Element:
[1, 3, 5]


In [4]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from start to end index (inclusive).
    Parameters:
        lst (list): Input list.
        start (int): Starting index.
        end (int): Ending index (inclusive).
    Returns:
        list: Sublist from start to end.
    """
    return lst[start:end + 1]

print("2. Slice a Sublist:")
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

2. Slice a Sublist:
[3, 4, 5]


In [5]:
def reverse_list(lst):
    """
    Returns a reversed version of lst using slicing.
    Parameters:
        lst (list): Input list.
    Returns:
        list: Reversed list.
    """
    return lst[::-1]

print("3. Reverse a List:")
print(reverse_list([1, 2, 3, 4, 5]))

3. Reverse a List:
[5, 4, 3, 2, 1]


In [6]:
def remove_first_last(lst):
    """
    Returns lst without its first and last elements.
    Parameters:
        lst (list): Input list.
    Returns:
        list: List without first and last elements.
    """
    return lst[1:-1]

print("4. Remove First and Last:")
print(remove_first_last([1, 2, 3, 4, 5]))

4. Remove First and Last:
[2, 3, 4]


In [7]:
def get_first_n(lst, n):
    """
    Returns the first n elements of lst.
    Parameters:
        lst (list): Input list.
        n (int): Number of elements to extract.
    Returns:
        list: First n elements.
    """
    return lst[:n]

print("5. Get First n Elements:")
print(get_first_n([1, 2, 3, 4, 5], 3))

5. Get First n Elements:
[1, 2, 3]


In [8]:
def get_last_n(lst, n):
    """
    Returns the last n elements of lst.
    Parameters:
        lst (list): Input list.
        n (int): Number of elements to extract from the end.
    Returns:
        list: Last n elements.
    """
    return lst[-n:]

print("6. Get Last n Elements:")
print(get_last_n([1, 2, 3, 4, 5], 2))

6. Get Last n Elements:
[4, 5]


In [9]:
def reverse_skip(lst):
    """
    Returns every second element starting from second-to-last, moving backward.
    Parameters:
        lst (list): Input list.
    Returns:
        list: Elements in reverse order skipping one each time.
    """
    return lst[-2::-2]

print("7. Reverse Skip:")
print(reverse_skip([1, 2, 3, 4, 5, 6]))

7. Reverse Skip:
[5, 3, 1]


---
## 4.3 Exercise on Nested Lists

In [10]:
def flatten(lst):
    """
    Flattens a nested list into a single 1D list.
    Parameters:
        lst (list): A nested list.
    Returns:
        list: A flat list containing all elements.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

print("1. Flatten:", flatten([[1, 2], [3, 4], [5]]))

1. Flatten: [1, 2, 3, 4, 5]


In [11]:
def access_nested_element(lst, indices):
    """
    Accesses an element in a nested list using a list of indices.
    Parameters:
        lst (list): A nested list.
        indices (list): A list of integer indices.
    Returns:
        The element at the specified position.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("2. Access Nested Element:", access_nested_element(lst, [1, 2]))

2. Access Nested Element: 6


In [12]:
def sum_nested(lst):
    """
    Recursively sums all elements in a nested list.
    Parameters:
        lst (list): A nested list of numbers.
    Returns:
        float: Sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print("3. Sum Nested:", sum_nested([[1, 2], [3, [4, 5]], 6]))

3. Sum Nested: 21


In [13]:
def remove_element(lst, elem):
    """
    Removes all occurrences of elem from a nested list.
    Parameters:
        lst (list): A nested list.
        elem: The element to remove.
    Returns:
        list: Nested list with all occurrences of elem removed.
    """
    return [remove_element(item, elem) if isinstance(item, list)
            else item for item in lst if item != elem]

print("4. Remove Element:", remove_element([[1, 2], [3, 2], [4, 5]], 2))

4. Remove Element: [[1], [3], [4, 5]]


In [14]:
def find_max(lst):
    """
    Finds the maximum element in a nested list of any depth.
    Parameters:
        lst (list): A nested list of numbers.
    Returns:
        The maximum value found.
    """
    flat = flatten(lst)
    return max(flat)

print("5. Find Max:", find_max([[1, 2], [3, [4, 5]], 6]))

5. Find Max: 6


In [15]:
def count_occurrences(lst, elem):
    """
    Counts how many times elem appears in a nested list.
    Parameters:
        lst (list): A nested list.
        elem: The element to count.
    Returns:
        int: Number of occurrences of elem.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print("6. Count Occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

6. Count Occurrences: 3


In [16]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list of any depth into a single list.
    Parameters:
        lst (list): A deeply nested list.
    Returns:
        list: A fully flattened single list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print("7. Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.
    Parameters:
        lst (list): A nested list of numbers.
    Returns:
        float: The average of all elements.
    """
    flat = flatten(lst)
    return sum(flat) / len(flat)

print("8. Average Nested:", average_nested([[1, 2], [3, 4], [5, 6]]))

8. Average Nested: 3.5


---
# Section 10: TO-DO NumPy
## 10.1 Basic Vector and Matrix Operations with NumPy

In [18]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


### Problem 1 — Array Creation

In [19]:
empty_arr = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_arr)

ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_arr)

filled_arr = np.full((3, 3), 7)
print("\n3. Full array (3x3 filled with 7):\n", filled_arr)

existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(existing)
print("\n4. zeros_like:\n", zeros_like_arr)

ones_like_arr = np.ones_like(existing)
print("\n5. ones_like:\n", ones_like_arr)

new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. List to NumPy array:", np_array)

1. Empty 2x2 array:
 [[6.59158385e-310 4.36806520e-315]
 [6.59158262e-310 6.59157267e-310]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like:
 [[0 0 0]
 [0 0 0]]

5. ones_like:
 [[1 1 1]
 [1 1 1]]

6. List to NumPy array: [1 2 3 4]


### Problem 2 — Array Manipulation: Numerical Ranges and Indexing

In [20]:
arr_10_49 = np.arange(10, 50)
print("1. Array 10 to 49:\n", arr_10_49)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):\n", matrix_3x3)

identity = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity)

rand_arr = np.random.random(30)
print("\n4. Random array (size 30) mean:", rand_arr.mean())

rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 array — Min:", rand_10x10.min(), "| Max:", rand_10x10.max())

zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:", reversed_arr)

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. Array with 1 on border, 0 inside:\n", border_arr)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard 8x8:\n", checkerboard)

1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30) mean: 0.5233134907902602

5. 10x10 array — Min: 0.00604888120991709 | Max: 0.9860799254009897

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Array with 1 on border, 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem 3 — Array Operations

In [21]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("1. x + y:\n", x + y)

print("\n2. x - y:\n", x - y)

print("\n3. x * 3:\n", x * 3)

print("\n4. x squared:\n", np.square(x))

print("\n5a. Dot v·w:", np.dot(v, w))
print("5b. Dot x·v:\n", np.dot(x, v))
print("5c. Dot x·y:\n", np.dot(x, y))

concat_xy_rows = np.concatenate((x, y), axis=0)
print("\n6a. Concatenate x & y along rows:\n", concat_xy_rows)

concat_vw_col = np.vstack((v, w))
print("6b. Concatenate v & w (vstack):\n", concat_vw_col)

print("\n7. Attempting to concatenate x and v...")
try:
    result = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"Error: {e}")
    print("Explanation: x has shape", x.shape, "and v has shape", v.shape,
          "- different number of dimensions (2D vs 1D), so concatenation fails.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5a. Dot v·w: 219
5b. Dot x·v:
 [29 77]
5c. Dot x·y:
 [[19 22]
 [50 58]]

6a. Concatenate x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v & w (vstack):
 [[ 9 10]
 [11 12]]

7. Attempting to concatenate x and v...
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x has shape (2, 2) and v has shape (2,) - different number of dimensions (2D vs 1D), so concatenation fails.


### Problem 4 — Matrix Operations

In [22]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = np.round(np.dot(A, A_inv))
print("1. A × A⁻¹ = I (rounded):\n", identity_check)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))

AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_T)
print("   B^T × A^T:\n", BT_AT)
print("   Equal?", np.array_equal(AB_T, BT_AT))

1. A × A⁻¹ = I (rounded):
 [[1. 0.]
 [0. 1.]]

2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB == BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T × A^T:
 [[23 51]
 [13 29]]
   Equal? True


In [23]:
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

B_sys = np.array([-1, -3, 9])

A_inv_sys = np.linalg.inv(A_sys)
X_inverse = np.dot(A_inv_sys, B_sys)
print("Solution using Inverse Method:")
print(f"  x = {X_inverse[0]:.4f}, y = {X_inverse[1]:.4f}, z = {X_inverse[2]:.4f}")

X_solve = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:")
print(f"  x = {X_solve[0]:.4f}, y = {X_solve[1]:.4f}, z = {X_solve[2]:.4f}")

Solution using Inverse Method:
  x = 2.0000, y = 1.0000, z = -2.0000

Solution using np.linalg.solve:
  x = 2.0000, y = 1.0000, z = -2.0000


---
## 10.2 Experiment — How Fast is NumPy?

In [24]:
import time
import numpy as np

SIZE = 1_000_000
a_list = list(range(SIZE))
b_list = list(range(SIZE))
a_np = np.arange(SIZE, dtype=float)
b_np = np.arange(SIZE, dtype=float)

print("=" * 55)
print(f"{'Operation':<25} {'Python List':>12} {'NumPy':>10} {'Speedup':>8}")
print("=" * 55)

t0 = time.time()
result = [a_list[i] + b_list[i] for i in range(SIZE)]
t_list_add = time.time() - t0
t0 = time.time()
result = a_np + b_np
t_np_add = time.time() - t0
print(f"{'Addition':<25} {t_list_add:>11.4f}s {t_np_add:>9.4f}s {t_list_add/t_np_add:>7.1f}x")

t0 = time.time()
result = [a_list[i] * b_list[i] for i in range(SIZE)]
t_list_mul = time.time() - t0
t0 = time.time()
result = a_np * b_np
t_np_mul = time.time() - t0
print(f"{'Multiplication':<25} {t_list_mul:>11.4f}s {t_np_mul:>9.4f}s {t_list_mul/t_np_mul:>7.1f}x")

t0 = time.time()
dot_list = sum(a_list[i] * b_list[i] for i in range(SIZE))
t_list_dot = time.time() - t0
t0 = time.time()
dot_np = np.dot(a_np, b_np)
t_np_dot = time.time() - t0
print(f"{'Dot Product':<25} {t_list_dot:>11.4f}s {t_np_dot:>9.4f}s {t_list_dot/t_np_dot:>7.1f}x")

MSIZE = 200
m_list = [[1.0]*MSIZE for _ in range(MSIZE)]
m_np_a = np.ones((MSIZE, MSIZE))
m_np_b = np.ones((MSIZE, MSIZE))

t0 = time.time()
result_mat_list = [[sum(m_list[i][k] * m_list[k][j] for k in range(MSIZE))
                    for j in range(MSIZE)] for i in range(MSIZE)]
t_list_mat = time.time() - t0
t0 = time.time()
result_mat_np = np.dot(m_np_a, m_np_b)
t_np_mat = time.time() - t0
print(f"{'Matrix Multiply (200x200)':<25} {t_list_mat:>11.4f}s {t_np_mat:>9.4f}s {t_list_mat/t_np_mat:>7.1f}x")

print("=" * 55)

Operation                  Python List      NumPy  Speedup
Addition                       0.1106s    0.0184s     6.0x
Multiplication                 0.1049s    0.0169s     6.2x
Dot Product                    0.1092s    0.0016s    69.4x
Matrix Multiply (200x200)      0.7772s    0.0013s   606.4x
